package com.pim.enums;

public enum Modules {
	
	HOMEPAGE,
	DENTAL_CATALOG,
	ITEM_CREATION,
	MEDICAL_CATALOG,
	SPECIAL_MARKET_CATALOG,
	ZAHN_CATALOG,
	ALL_CATALOG,
	SEO,
	CLASSIFICATION,
	ITEM_MESSAGE,
	WEB_DESCRIPTION,
	CANADA_TRANSLATION,
	LOCAL_ATTRIBUTE,
	ITEM_MESSAGES,
	User_Role,
    Entities_UI_Func,
	DataEntities_Attributes,
    MiddleWare,
    WorkFlow,
    SubstituteCatalogRule,
    GLOBAL_ATTRIBUTE,
    JDE_ITEMCREATION,
    UIFUCTIONAL_TASK,
    catalogAssignment,
    DENTAL_CATALOG_CA,
    French_DESCRIPTION,
    AddCatalogs,
    FDM,
    DamUserRole,
    DAM_Workflow,
    DAMUIFUNCTIONALITY, 
    GEP_WEB_DESCRIPTION,
    DAM_Workflow_NewFeatures,
    DAMWorkflow_ImageUploadStandaloneTest,
    DAM_MultiRegionAccess,
    DAM_Viva_Learning,
    JSON_Verification_DAM,
    JSON_Verification_PIM,
    DAMUI_NewFeatures,
    Akmai_Tests,
    AssetsAssignmentsDelete_pdf,
    AssetsAssignmentsDelete_img,
    DAMToPIM_Workflow,
    VerificationPart,
    Prices
      
}

